### ISSUE TITLE
Saving 'about.html' failed: tmpl is not defined (vs_code-message)

### ISSUE THREAD

**Issue by dmitrijLo** [goessner/microjam#8]
microJam is not converting the markdown files into html if you set up a new project as described in the documentation (without cloning a template-repository) ; probably since the new version v0.3.7.

error_message:
<img width="455" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/60650495/85158966-26bf5f00-b25d-11ea-9231-f962ce9a59d7.png">

probably the issue:
<img width="455" alt="PastedGraphic-2" src="https://user-images.githubusercontent.com/60650495/85159008-363ea800-b25d-11ea-8529-a6167c7182a4.png">

**Comment by goessner** [comment]
yes ... most likely the issue.

resolved starting from version 0.3.8 in (hopefully) all relevant `template.js` files.

thanks
